name: Unit tests
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        fhir-sequence: [STU3, R4B, R5]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.6.11"
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python packages
      run: |
        uv add "fhir.resources[xml]>=7.0.0,<8.0.0"
        uv sync --all-extras --dev
    - name: Run tests
      env:
        FHIR_SEQUENCE: ${{ matrix.fhir-sequence }}
      run: uv run pytest
  run-tests-r4:
    needs: run-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        fhir-sequence: [R4]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.6.11"
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python packages
      run: |
        uv add "fhir.resources[xml]==6.4.0"
        uv sync --all-extras --dev
    - name: Run tests
      env:
        FHIR_SEQUENCE: ${{ matrix.fhir-sequence }}
      run: uv run pytest
  run-tests-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        fhir-sequence: [R5]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.6.11"
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python packages
      run: |
        uv add "fhir.resources[xml]>=7.0.0,<8.0.0"
        uv sync --all-extras --dev
    - name: Run tests
      env:
        FHIR_SEQUENCE: ${{ matrix.fhir-sequence }}
      run: uv run pytest
