name: Unit tests
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        fhir-sequence: [STU3, R4B, R5]
    steps:
    - uses: actions/checkout@v4
    - name: Install Poetry
      run: pipx install poetry
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install Python packages
      run: poetry install
    - name: Run tests
      env:
        FHIR_SEQUENCE: ${{ matrix.fhir-sequence }}
      run: poetry run pytest
  run-tests-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.13"]
        fhir-sequence: [R5]
    steps:
    - uses: actions/checkout@v4
    - name: Install Poetry
      run: pipx install poetry
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install Python packages
      run: poetry install
    - name: Run tests
      env:
        FHIR_SEQUENCE: ${{ matrix.fhir-sequence }}
      run: poetry run pytest
