name: Unit tests
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        fhir-sequence: [STU3, R4B, R5]
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Run tests
      env:
        FHIR_SEQUENCE: ${{ matrix.fhir-sequence }}
      run: uv run --frozen pytest
  run-tests-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.14"]
        fhir-sequence: [R5]
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Run tests
      env:
        FHIR_SEQUENCE: ${{ matrix.fhir-sequence }}
      run: uv run --frozen pytest
